spring:
  application:
    name: online-shop-telegram-bot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/sh_z_market_db
    username: zafar_mvps
    password: 122333
    # Skrinshotdagi 'Internal Database URL' ni shu yerga qo'ying
#    url: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/sh-z-market-bot-db?prepareThreshold=0
#    username: postgres.oufxlbplqyezflrmkuzl
#    password: "KLJAHSN(){APOJS+)(H)*{B(U"
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://dpg-d605e9fpm1nc73d2secg-a.oregon-postgres.render.com:5432/db_bq3r
#    username: db_bq3r_user
#    password: "nrg2Mz7JnV6LLsRav7MsanVCLk32GDvj"
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
telegram:
  app:
    customer:
      products:
        webb-app:
          url: ${CUSTOMER_WEB_APP:}/#
    seller:
      commentary:
        webapp:
          url: ${COMMENTARY_SELLER_WEBAPP:}
      finance:
        webapp:
          url: ${FINANCE_SELLER_WEBAPP:}/#
      payment:
        webapp:
          url: ${PAYMENT_SELLER_WEBAPP:}/#
      order:
        webapp:
          url: ${ORDER_SELLER_WEBAPP:}/#
      confirm:
        webapp:
          url: ${VERIFY_SELLER_WEBAPP:}/#
      product:
        webapp:
          url: ${PRODUCT_SELLER_WEBAPP:}/#
      shop:
        webapp:
          url: ${SHOP_SELLER_WEBAPP:}
  api:
    security:
      api-token: ZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNclianCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNclianCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDclianCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANclianCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNclianCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLI


  #base-url: https://believes-lovers-firefox-activities.trycloudflare.com
  base-url: https://codebyz.online
  users:
    bot:
      token: 7613682792:AAGK6v1xGHdSI1033idh9OP7Xx-jslCwmvA
      username: https://t.me/sh_z_friends_market_robot
      webhook-path: /telegram/users/webhook
  admins:
    bot:
      token: 7950562377:AAG6_kmjkf6SnkNNPtNbHBk7TzmixMivYJg
      username: https://t.me/OnlineShopAdminsBot
      webhook-path: /telegram/admins/webhook
  sellers:
    bot:
      token: 8564453232:AAGtf3A4Loru1QeyS_kodtyJktPqKenJWe4
      username: https://t.me/onlineShopSellersBot
      webhook-path: /telegram/sellers/webhook
  super-admin:
    bot:
      token: 8290850848:AAHOTyuDYnLFpOz_vMBXCmNRMGgM_i9q5fU
      username: https://t.me/ssasldncabot
      webhook-path: /telegram/super-admin/webhook
springdoc:
  override-with-generic-response: false
  swagger-ui:
    path: /swagger
    config-url: /v3/api-docs
    disable-swagger-default-url: true
app:
  timezone: Asia/Tashkent
brevo:
  api:
    key: ${BREVO_API_KEY:}

verified:
  email:
    time:
      milli:
        second: 120000
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration:
    ms: 3600000000000
  refresh:
    expiration:
      ms: 3600000000000
