spring:
  application:
    name: online-shop-telegram-bot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/sh_z_market_db
    #    url: jdbc:postgresql://127.0.0.1:5432/online-shot-bot
    username: postgres
    password: 122333
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
telegram:
  app:
    customer:
      products:
        webb-app:
          url: https://quickly-versions-questionnaire-produces.trycloudflare.com/#
    seller:
      commentary:
        webapp:
          url: https://identify-screen-substantially-affecting.trycloudflare.com
      finance:
        webapp:
          url: https://metals-desire-accountability-total.trycloudflare.com/#
      payment:
        webapp:
          url: https://buy-florist-roland-forth.trycloudflare.com/#
      order:
        webapp:
          url: https://imperial-showers-nutrition-opponents.trycloudflare.com/#
      confirm:
        webapp:
          url: https://format-rapids-after-her.trycloudflare.com/#
      product:
        webapp:
          url: https://isolation-expects-originally-korean.trycloudflare.com/#
      shop:
        webapp:
          url: https://examinations-began-your-pin.trycloudflare.com
  api:
    security:
      api-token: ZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNclianCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNclianCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDclianCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANclianCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNclianCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLIZAFARJNCDSAJHASJDNCLANSDCNALSDNCAILNDCAISLNDCALISNCLASDNCALISNDCLAISNDCASNCDALSCNALSDJNAALKNDCLAISNCLIANCLIANSDCLIASNDCILASNCLIANDLCAINSUDJCNALISNDCISAKJDCNKALSNJDCAINCLAISNCLASUNDCLAISNDCILANLCIDNASLDCINASINDCIDASNILANSDCNLI


  base-url: https://believes-lovers-firefox-activities.trycloudflare.com
  users:
    bot:
      token: 7613682792:AAGK6v1xGHdSI1033idh9OP7Xx-jslCwmvA
      username: https://t.me/sh_z_friends_market_robot
      webhook-path: /telegram/users/webhook
  admins:
    bot:
      token: 7950562377:AAG6_kmjkf6SnkNNPtNbHBk7TzmixMivYJg
      username: https://t.me/OnlineShopAdminsBot
      webhook-path: /telegram/admins/webhook
  sellers:
    bot:
      token: 8564453232:AAGtf3A4Loru1QeyS_kodtyJktPqKenJWe4
      username: https://t.me/onlineShopSellersBot
      webhook-path: /telegram/sellers/webhook
  super-admin:
    bot:
      token: 8290850848:AAHOTyuDYnLFpOz_vMBXCmNRMGgM_i9q5fU
      username: https://t.me/ssasldncabot
      webhook-path: /telegram/super-admin/webhook
springdoc:
  swagger-ui:
    path: /swagger
    config-url: /v3/api-docs
    disable-swagger-default-url: true
app:
  timezone: Asia/Tashkent
brevo:
  api:
    key: ${BREVO_API_KEY}

verified:
  email:
    time:
      milli:
        second: 120000
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration:
    ms: 3600000000000
  refresh:
    expiration:
      ms: 3600000000000